// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_saves_upload_saveSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_saves-upload_save'
} as const;

export const Body_saves_upload_save_streamSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_saves-upload_save_stream'
} as const;

export const BuildChangeSchema = {
    properties: {
        build_id: {
            type: 'string',
            title: 'Build Id',
            default: ''
        },
        build_name: {
            type: 'string',
            title: 'Build Name',
            default: ''
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index',
            default: -1
        },
        status: {
            type: 'string',
            enum: ['improved', 'degraded', 'reordered', 'unchanged', 'new', 'broken_pin', 'potentially_affected'],
            title: 'Status'
        },
        best_before: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Best Before'
        },
        best_after: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Best After'
        },
        delta: {
            type: 'integer',
            title: 'Delta',
            default: 0
        },
        entered: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Entered'
        },
        left: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Left'
        },
        pinned_removed: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Pinned Removed'
        },
        relevant_added: {
            type: 'integer',
            title: 'Relevant Added',
            default: 0
        },
        cause: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['relics', 'build_edit', 'game_data', 'mixed']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cause'
        },
        reliable: {
            type: 'boolean',
            title: 'Reliable',
            default: true
        }
    },
    type: 'object',
    required: ['status'],
    title: 'BuildChange',
    description: `How a build's optimal arrangement changed between two optimization inputs.

Produced two ways with the same shape: a cheap relic-diff at save-upload
time (\`\`potentially_affected\`\` / \`\`broken_pin\`\`), and a precise recompute on
optimize (\`\`improved\`\` / \`\`degraded\`\` / \`\`reordered\`\` / \`\`unchanged\`\`).
\`\`reliable\`\` is False when a truncated (non-exhaustive) search makes a small
delta untrustworthy.  Relics are referenced by content, never by ga_handle.`
} as const;

export const BuildCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        character: {
            type: 'string',
            maxLength: 50,
            title: 'Character'
        },
        groups: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groups'
        }
    },
    type: 'object',
    required: ['name', 'character'],
    title: 'BuildCreate'
} as const;

export const BuildDefinitionSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                '$ref': '#/components/schemas/WeightGroup'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep',
            default: true
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max',
            default: 1
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight',
            default: 0
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        }
    },
    type: 'object',
    required: ['id', 'name', 'character'],
    title: 'BuildDefinition',
    description: 'User-defined build configuration. Stable API schema.'
} as const;

export const BuildPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep'
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max'
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'name', 'character', 'include_deep', 'curse_max', 'default_curse_weight', 'is_featured'],
    title: 'BuildPublic'
} as const;

export const BuildSnapshotSummarySchema = {
    properties: {
        build_id: {
            type: 'string',
            title: 'Build Id'
        },
        change: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildChange'
                },
                {
                    type: 'null'
                }
            ]
        },
        reviewed: {
            type: 'boolean',
            title: 'Reviewed',
            default: true
        },
        best_score: {
            type: 'integer',
            title: 'Best Score',
            default: 0
        },
        computed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Computed At'
        }
    },
    type: 'object',
    required: ['build_id'],
    title: 'BuildSnapshotSummary',
    description: `A build's most recent optimization change.

Embeds the full :class:\`BuildChange\` so the frontend can render rich,
relic-aware change text (verdict + relative % + which relics moved) and
filter on \`\`reviewed\`\` — all without a full snapshot load.  Deciding which
changes are "interesting" is left to the frontend formatter.`
} as const;

export const BuildUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        character: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Character'
        },
        groups: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groups'
        },
        required_effects: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Effects'
        },
        required_families: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Families'
        },
        excluded_effects: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Effects'
        },
        excluded_families: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Families'
        },
        include_deep: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Include Deep'
        },
        curse_max: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Curse Max'
        },
        default_curse_weight: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Effect Limits'
        },
        family_limits: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Limits'
        },
        family_weight_floors: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Weight Floors'
        }
    },
    type: 'object',
    title: 'BuildUpdate'
} as const;

export const BuildsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BuildPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BuildsPublic'
} as const;

export const CumulativeEffectGroupSchema = {
    properties: {
        family: {
            type: 'string',
            title: 'Family'
        },
        mode: {
            type: 'string',
            enum: ['multiplicative', 'multiplicative_reduction', 'additive_flat'],
            title: 'Mode'
        },
        unit: {
            type: 'string',
            title: 'Unit'
        },
        tiers: {
            items: {
                '$ref': '#/components/schemas/CumulativeEffectTier'
            },
            type: 'array',
            title: 'Tiers'
        },
        cumulative_value: {
            type: 'number',
            title: 'Cumulative Value'
        },
        bonus_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bonus Percent'
        },
        bonus_display: {
            type: 'string',
            title: 'Bonus Display'
        },
        conditional: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conditional'
        },
        is_top: {
            type: 'boolean',
            title: 'Is Top',
            default: false
        }
    },
    type: 'object',
    required: ['family', 'mode', 'unit', 'tiers', 'cumulative_value', 'bonus_display'],
    title: 'CumulativeEffectGroup',
    description: `Cumulative in-game bonus for one effect family across a whole vessel.

Computed at serve time by nrplanner.cumulative.summarize_cumulative_effects
from the curated per-effect values in resources/json/effect_bonus_values.json.
Self-stackable numeric effects (incl. family-less singletons) produce a group;
conditional ones (e.g. "at low HP") set \`\`conditional\`\` so the UI can badge them.`
} as const;

export const CumulativeEffectTierSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        tier_label: {
            type: 'string',
            title: 'Tier Label'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['name', 'tier_label', 'count'],
    title: 'CumulativeEffectTier',
    description: "One tier within a stacked-effect group (e.g. '+4' present 3 times)."
} as const;

export const DebugExportRequestSchema = {
    properties: {
        mode: {
            type: 'string',
            enum: ['view', 'full'],
            title: 'Mode',
            default: 'full'
        },
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        results: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Results'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'DebugExportRequest'
} as const;

export const FeaturedBuildPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep'
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max'
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'character', 'include_deep', 'curse_max', 'default_curse_weight'],
    title: 'FeaturedBuildPublic'
} as const;

export const FeaturedBuildsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeaturedBuildPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeaturedBuildsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LockedSlotSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        }
    },
    type: 'object',
    required: ['slot_index', 'ga_handle'],
    title: 'LockedSlot',
    description: 'A relic frozen in its exact slot during a single-slot re-optimization.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OptimizeRequestSchema = {
    properties: {
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        build: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildDefinition'
                },
                {
                    type: 'null'
                }
            ]
        },
        relics: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/OwnedRelic-Input'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relics'
        },
        top_n: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Top N',
            default: 10
        },
        max_per_vessel: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Max Per Vessel',
            default: 3
        }
    },
    type: 'object',
    title: 'OptimizeRequest'
} as const;

export const OwnedRelic_InputSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effects', 'curses', 'is_deep', 'name', 'tier'],
    title: 'OwnedRelic',
    description: 'A relic owned by the player, parsed from save data.'
} as const;

export const OwnedRelic_OutputSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        effect_count: {
            type: 'integer',
            title: 'Effect Count',
            readOnly: true
        },
        curse_count: {
            type: 'integer',
            title: 'Curse Count',
            readOnly: true
        },
        all_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'All Effects',
            readOnly: true
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effects', 'curses', 'is_deep', 'name', 'tier', 'effect_count', 'curse_count', 'all_effects'],
    title: 'OwnedRelic',
    description: 'A relic owned by the player, parsed from save data.'
} as const;

export const ParsedProfileDataSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        relic_count: {
            type: 'integer',
            title: 'Relic Count'
        },
        relics: {
            items: {
                '$ref': '#/components/schemas/ParsedRelicData'
            },
            type: 'array',
            title: 'Relics'
        },
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        }
    },
    type: 'object',
    required: ['slot_index', 'name', 'relic_count', 'relics'],
    title: 'ParsedProfileData'
} as const;

export const ParsedRelicDataSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effect_1: {
            type: 'integer',
            title: 'Effect 1'
        },
        effect_2: {
            type: 'integer',
            title: 'Effect 2'
        },
        effect_3: {
            type: 'integer',
            title: 'Effect 3'
        },
        curse_1: {
            type: 'integer',
            title: 'Curse 1'
        },
        curse_2: {
            type: 'integer',
            title: 'Curse 2'
        },
        curse_3: {
            type: 'integer',
            title: 'Curse 3'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effect_1', 'effect_2', 'effect_3', 'curse_1', 'curse_2', 'curse_3', 'is_deep', 'name', 'tier'],
    title: 'ParsedRelicData',
    description: 'OwnedRelic data as returned in the upload response (before DB persistence).'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        save_upload_id: {
            type: 'string',
            format: 'uuid',
            title: 'Save Upload Id'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'save_upload_id', 'slot_index', 'name'],
    title: 'ProfilePublic'
} as const;

export const ProfilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfilesPublic'
} as const;

export const RelicDeltaSchema = {
    properties: {
        added: {
            type: 'integer',
            title: 'Added',
            default: 0
        },
        removed: {
            type: 'integer',
            title: 'Removed',
            default: 0
        }
    },
    type: 'object',
    title: 'RelicDelta',
    description: 'How many relics were gained/lost versus the previous save.'
} as const;

export const RelicPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effect_1: {
            type: 'integer',
            title: 'Effect 1'
        },
        effect_2: {
            type: 'integer',
            title: 'Effect 2'
        },
        effect_3: {
            type: 'integer',
            title: 'Effect 3'
        },
        curse_1: {
            type: 'integer',
            title: 'Curse 1'
        },
        curse_2: {
            type: 'integer',
            title: 'Curse 2'
        },
        curse_3: {
            type: 'integer',
            title: 'Curse 3'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['id', 'profile_id', 'ga_handle', 'item_id', 'real_id', 'color', 'effect_1', 'effect_2', 'effect_3', 'curse_1', 'curse_2', 'curse_3', 'is_deep', 'name', 'tier'],
    title: 'RelicPublic'
} as const;

export const RelicRefSchema = {
    properties: {
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        name: {
            type: 'string',
            title: 'Name',
            default: ''
        },
        color: {
            type: 'string',
            title: 'Color',
            default: ''
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        }
    },
    type: 'object',
    required: ['real_id'],
    title: 'RelicRef',
    description: 'Lightweight relic identity for change display (no ga_handle — unstable).'
} as const;

export const RelicsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RelicPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RelicsPublic'
} as const;

export const SaveStatusPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        uploaded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uploaded At'
        },
        profile_count: {
            type: 'integer',
            title: 'Profile Count'
        },
        profile_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Profile Names'
        }
    },
    type: 'object',
    required: ['id', 'platform', 'profile_count', 'profile_names'],
    title: 'SaveStatusPublic',
    description: "Lightweight status of the user's most recent save upload."
} as const;

export const SlotAlternativeRequestSchema = {
    properties: {
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        build: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildDefinition'
                },
                {
                    type: 'null'
                }
            ]
        },
        relics: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/OwnedRelic-Input'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relics'
        },
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        struck_slot_index: {
            type: 'integer',
            title: 'Struck Slot Index'
        },
        locked_slots: {
            items: {
                '$ref': '#/components/schemas/LockedSlot'
            },
            type: 'array',
            title: 'Locked Slots'
        },
        excluded_ga_handles: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Ga Handles'
        }
    },
    type: 'object',
    required: ['vessel_id', 'struck_slot_index'],
    title: 'SlotAlternativeRequest',
    description: `Re-optimize a single vessel slot, freezing every other slot in place.

Powers the "strike a relic" UI: keep each relic in \`\`locked_slots\`\` in its
exact slot, exclude the struck relic(s), and re-fill only
\`\`struck_slot_index\`\` with the next-best relic.  Freezing positions (rather
than positionless pinning) guarantees the rest of the layout — and its
scores — stay put, so the total moves only as a function of the struck slot.
Same dual-mode inventory inputs as :class:\`OptimizeRequest\` (DB mode =
build_id + profile_id; inline mode = build + relics).  Persists nothing.`
} as const;

export const SlotAssignmentSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        slot_color: {
            type: 'string',
            title: 'Slot Color'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        relic: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OwnedRelic-Output'
                },
                {
                    type: 'null'
                }
            ]
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        breakdown: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Breakdown'
        }
    },
    type: 'object',
    required: ['slot_index', 'slot_color', 'is_deep', 'score', 'breakdown'],
    title: 'SlotAssignment',
    description: 'A relic assigned to one vessel slot.'
} as const;

export const SnapshotResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/VesselResult'
            },
            type: 'array',
            title: 'Results'
        },
        last_change: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildChange'
                },
                {
                    type: 'null'
                }
            ]
        },
        computed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Computed At'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'SnapshotResponse',
    description: 'Cached optimization results from a fresh snapshot.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UploadResponseSchema = {
    properties: {
        platform: {
            type: 'string',
            title: 'Platform'
        },
        profile_count: {
            type: 'integer',
            title: 'Profile Count'
        },
        profiles: {
            items: {
                '$ref': '#/components/schemas/ParsedProfileData'
            },
            type: 'array',
            title: 'Profiles'
        },
        save_upload_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Save Upload Id'
        },
        persisted: {
            type: 'boolean',
            title: 'Persisted',
            default: false
        },
        relic_delta: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RelicDelta'
                },
                {
                    type: 'null'
                }
            ]
        },
        affected_builds: {
            items: {
                '$ref': '#/components/schemas/BuildChange'
            },
            type: 'array',
            title: 'Affected Builds'
        }
    },
    type: 'object',
    required: ['platform', 'profile_count', 'profiles'],
    title: 'UploadResponse'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VesselResultSchema = {
    properties: {
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        vessel_name: {
            type: 'string',
            title: 'Vessel Name'
        },
        vessel_character: {
            type: 'string',
            title: 'Vessel Character'
        },
        unlock_flag: {
            type: 'integer',
            title: 'Unlock Flag'
        },
        slot_colors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Slot Colors'
        },
        assignments: {
            items: {
                '$ref': '#/components/schemas/SlotAssignment'
            },
            type: 'array',
            title: 'Assignments'
        },
        total_score: {
            type: 'integer',
            title: 'Total Score'
        },
        meets_requirements: {
            type: 'boolean',
            title: 'Meets Requirements',
            default: true
        },
        missing_requirements: {
            items: {
                anyOf: [
                    {
                        type: 'integer'
                    },
                    {
                        type: 'string'
                    }
                ]
            },
            type: 'array',
            title: 'Missing Requirements'
        },
        search_truncated: {
            type: 'boolean',
            title: 'Search Truncated',
            default: false
        },
        cumulative_effects: {
            items: {
                '$ref': '#/components/schemas/CumulativeEffectGroup'
            },
            type: 'array',
            title: 'Cumulative Effects'
        }
    },
    type: 'object',
    required: ['vessel_id', 'vessel_name', 'vessel_character', 'unlock_flag', 'slot_colors', 'assignments', 'total_score'],
    title: 'VesselResult',
    description: 'Optimization result for a single vessel. Ready as FastAPI response.'
} as const;

export const WeightGroupSchema = {
    properties: {
        weight: {
            type: 'integer',
            title: 'Weight'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Families'
        }
    },
    type: 'object',
    required: ['weight'],
    title: 'WeightGroup',
    description: 'A user-defined group of effects/families sharing a scoring weight.'
} as const;