// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_saves_export_add_relicsSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        specs: {
            type: 'string',
            title: 'Specs',
            default: '[]'
        },
        murk_delta: {
            type: 'integer',
            title: 'Murk Delta',
            default: 0
        }
    },
    type: 'object',
    required: ['file', 'slot_index'],
    title: 'Body_saves-export_add_relics'
} as const;

export const Body_saves_export_loadoutsSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        operations: {
            type: 'string',
            title: 'Operations',
            default: '[]'
        }
    },
    type: 'object',
    required: ['file', 'slot_index'],
    title: 'Body_saves-export_loadouts'
} as const;

export const Body_saves_export_saveSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        ga_handles: {
            type: 'string',
            title: 'Ga Handles',
            default: '[]'
        },
        favorite_changes: {
            type: 'string',
            title: 'Favorite Changes',
            default: '{}'
        }
    },
    type: 'object',
    required: ['file', 'slot_index'],
    title: 'Body_saves-export_save'
} as const;

export const Body_saves_rites_planSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        build_ids: {
            type: 'string',
            title: 'Build Ids',
            default: '[]'
        },
        builds: {
            type: 'string',
            title: 'Builds',
            default: '[]'
        },
        buckets: {
            type: 'string',
            title: 'Buckets',
            default: '[]'
        },
        stop_mode: {
            type: 'string',
            title: 'Stop Mode',
            default: 'fixed'
        },
        budget: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget'
        },
        top_n: {
            type: 'integer',
            title: 'Top N',
            default: 10
        },
        inclusion_rules: {
            type: 'string',
            title: 'Inclusion Rules',
            default: '[]'
        },
        exclusion_rules: {
            type: 'string',
            title: 'Exclusion Rules',
            default: '[]'
        },
        sold_handles: {
            type: 'string',
            title: 'Sold Handles',
            default: '[]'
        },
        staged_mints: {
            type: 'string',
            title: 'Staged Mints',
            default: '[]'
        },
        staged_murk_delta: {
            type: 'integer',
            title: 'Staged Murk Delta',
            default: 0
        },
        staged_favorites: {
            type: 'string',
            title: 'Staged Favorites',
            default: '{}'
        }
    },
    type: 'object',
    required: ['file', 'slot_index'],
    title: 'Body_saves-rites_plan'
} as const;

export const Body_saves_rites_plan_streamSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        build_ids: {
            type: 'string',
            title: 'Build Ids',
            default: '[]'
        },
        builds: {
            type: 'string',
            title: 'Builds',
            default: '[]'
        },
        buckets: {
            type: 'string',
            title: 'Buckets',
            default: '[]'
        },
        stop_mode: {
            type: 'string',
            title: 'Stop Mode',
            default: 'fixed'
        },
        budget: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget'
        },
        top_n: {
            type: 'integer',
            title: 'Top N',
            default: 10
        },
        inclusion_rules: {
            type: 'string',
            title: 'Inclusion Rules',
            default: '[]'
        },
        exclusion_rules: {
            type: 'string',
            title: 'Exclusion Rules',
            default: '[]'
        },
        sold_handles: {
            type: 'string',
            title: 'Sold Handles',
            default: '[]'
        },
        staged_mints: {
            type: 'string',
            title: 'Staged Mints',
            default: '[]'
        },
        staged_murk_delta: {
            type: 'integer',
            title: 'Staged Murk Delta',
            default: 0
        },
        staged_favorites: {
            type: 'string',
            title: 'Staged Favorites',
            default: '{}'
        }
    },
    type: 'object',
    required: ['file', 'slot_index'],
    title: 'Body_saves-rites_plan_stream'
} as const;

export const Body_saves_upload_saveSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_saves-upload_save'
} as const;

export const Body_saves_upload_save_streamSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_saves-upload_save_stream'
} as const;

export const BuildChangeSchema = {
    properties: {
        build_id: {
            type: 'string',
            title: 'Build Id',
            default: ''
        },
        build_name: {
            type: 'string',
            title: 'Build Name',
            default: ''
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index',
            default: -1
        },
        status: {
            type: 'string',
            enum: ['improved', 'degraded', 'reordered', 'unchanged', 'new', 'broken_pin', 'potentially_affected'],
            title: 'Status'
        },
        best_before: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Best Before'
        },
        best_after: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Best After'
        },
        delta: {
            type: 'integer',
            title: 'Delta',
            default: 0
        },
        entered: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Entered'
        },
        left: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Left'
        },
        pinned_removed: {
            items: {
                '$ref': '#/components/schemas/RelicRef'
            },
            type: 'array',
            title: 'Pinned Removed'
        },
        relevant_added: {
            type: 'integer',
            title: 'Relevant Added',
            default: 0
        },
        causes: {
            items: {
                type: 'string',
                enum: ['relics', 'staged', 'build_edit', 'game_data']
            },
            type: 'array',
            title: 'Causes'
        },
        cause: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['relics', 'build_edit', 'game_data', 'mixed', 'staged']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cause'
        },
        reliable: {
            type: 'boolean',
            title: 'Reliable',
            default: true
        },
        comparable: {
            type: 'boolean',
            title: 'Comparable',
            default: true
        }
    },
    type: 'object',
    required: ['status'],
    title: 'BuildChange',
    description: `How a build's optimal arrangement changed between two optimization inputs.

Produced two ways with the same shape: a cheap relic-diff at save-upload
time (\`\`potentially_affected\`\` / \`\`broken_pin\`\`), and a precise recompute on
optimize (\`\`improved\`\` / \`\`degraded\`\` / \`\`reordered\`\` / \`\`unchanged\`\`).
\`\`reliable\`\` is False when a truncated (non-exhaustive) search makes a small
delta untrustworthy.  Relics are referenced by content, never by ga_handle.`
} as const;

export const BuildCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        character: {
            type: 'string',
            maxLength: 50,
            title: 'Character'
        },
        groups: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groups'
        }
    },
    type: 'object',
    required: ['name', 'character'],
    title: 'BuildCreate'
} as const;

export const BuildDefinitionSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                '$ref': '#/components/schemas/WeightGroup'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep',
            default: true
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max',
            default: 1
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight',
            default: 0
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        }
    },
    type: 'object',
    required: ['id', 'name', 'character'],
    title: 'BuildDefinition',
    description: 'User-defined build configuration. Stable API schema.'
} as const;

export const BuildPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep'
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max'
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'name', 'character', 'include_deep', 'curse_max', 'default_curse_weight', 'is_featured'],
    title: 'BuildPublic'
} as const;

export const BuildSnapshotSummarySchema = {
    properties: {
        build_id: {
            type: 'string',
            title: 'Build Id'
        },
        change: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildChange'
                },
                {
                    type: 'null'
                }
            ]
        },
        reviewed: {
            type: 'boolean',
            title: 'Reviewed',
            default: true
        },
        best_score: {
            type: 'integer',
            title: 'Best Score',
            default: 0
        },
        computed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Computed At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['build_id'],
    title: 'BuildSnapshotSummary',
    description: `A build's most recent optimization change.

Embeds the full :class:\`BuildChange\` so the frontend can render rich,
relic-aware change text (verdict + relative % + which relics moved) and
filter on \`\`reviewed\`\` — all without a full snapshot load.  Deciding which
changes are "interesting" is left to the frontend formatter.`
} as const;

export const BuildUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        character: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Character'
        },
        groups: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groups'
        },
        required_effects: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Effects'
        },
        required_families: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Families'
        },
        excluded_effects: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Effects'
        },
        excluded_families: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Families'
        },
        include_deep: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Include Deep'
        },
        curse_max: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Curse Max'
        },
        default_curse_weight: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Effect Limits'
        },
        family_limits: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Limits'
        },
        family_weight_floors: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'integer'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Family Weight Floors'
        }
    },
    type: 'object',
    title: 'BuildUpdate'
} as const;

export const BuildsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BuildPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BuildsPublic'
} as const;

export const CumulativeEffectGroupSchema = {
    properties: {
        family: {
            type: 'string',
            title: 'Family'
        },
        mode: {
            type: 'string',
            enum: ['multiplicative', 'multiplicative_reduction', 'additive_flat'],
            title: 'Mode'
        },
        unit: {
            type: 'string',
            title: 'Unit'
        },
        tiers: {
            items: {
                '$ref': '#/components/schemas/CumulativeEffectTier'
            },
            type: 'array',
            title: 'Tiers'
        },
        cumulative_value: {
            type: 'number',
            title: 'Cumulative Value'
        },
        bonus_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bonus Percent'
        },
        bonus_display: {
            type: 'string',
            title: 'Bonus Display'
        },
        conditional: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conditional'
        },
        is_top: {
            type: 'boolean',
            title: 'Is Top',
            default: false
        }
    },
    type: 'object',
    required: ['family', 'mode', 'unit', 'tiers', 'cumulative_value', 'bonus_display'],
    title: 'CumulativeEffectGroup',
    description: `Cumulative in-game bonus for one effect family across a whole vessel.

Computed at serve time by nrplanner.cumulative.summarize_cumulative_effects
from the curated per-effect values in resources/json/effect_bonus_values.json.
Self-stackable numeric effects (incl. family-less singletons) produce a group;
conditional ones (e.g. "at low HP") set \`\`conditional\`\` so the UI can badge them.`
} as const;

export const CumulativeEffectTierSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        tier_label: {
            type: 'string',
            title: 'Tier Label'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['name', 'tier_label', 'count'],
    title: 'CumulativeEffectTier',
    description: "One tier within a stacked-effect group (e.g. '+4' present 3 times)."
} as const;

export const CumulativeRequestSchema = {
    properties: {
        effect_id_groups: {
            items: {
                items: {
                    type: 'integer'
                },
                type: 'array'
            },
            type: 'array',
            title: 'Effect Id Groups'
        }
    },
    type: 'object',
    required: ['effect_id_groups'],
    title: 'CumulativeRequest'
} as const;

export const DebugExportRequestSchema = {
    properties: {
        mode: {
            type: 'string',
            enum: ['view', 'full'],
            title: 'Mode',
            default: 'full'
        },
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        results: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Results'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'DebugExportRequest'
} as const;

export const FeaturedBuildPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        groups: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Groups'
        },
        required_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Required Effects'
        },
        required_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Required Families'
        },
        excluded_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Effects'
        },
        excluded_families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Excluded Families'
        },
        include_deep: {
            type: 'boolean',
            title: 'Include Deep'
        },
        curse_max: {
            type: 'integer',
            title: 'Curse Max'
        },
        default_curse_weight: {
            type: 'integer',
            title: 'Default Curse Weight'
        },
        pinned_relics: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Pinned Relics'
        },
        excluded_stacking_categories: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Stacking Categories'
        },
        effect_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Effect Limits'
        },
        family_limits: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Limits'
        },
        family_weight_floors: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Family Weight Floors'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'character', 'include_deep', 'curse_max', 'default_curse_weight'],
    title: 'FeaturedBuildPublic'
} as const;

export const FeaturedBuildsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeaturedBuildPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeaturedBuildsPublic'
} as const;

export const GeneratedRelicPublicSchema = {
    properties: {
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        tier: {
            type: 'integer',
            title: 'Tier'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        odds_source: {
            type: 'string',
            title: 'Odds Source'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        effect_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Effect Names'
        },
        curse_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Curse Names'
        }
    },
    type: 'object',
    required: ['real_id', 'item_id', 'color', 'tier', 'is_deep', 'effects', 'curses', 'odds_source', 'name', 'effect_names', 'curse_names'],
    title: 'GeneratedRelicPublic',
    description: 'A rolled relic (effects/curses already in canonical save order).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoadoutRankSchema = {
    properties: {
        build_id: {
            type: 'string',
            title: 'Build Id'
        },
        rank: {
            type: 'integer',
            title: 'Rank'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        loadout_index: {
            type: 'integer',
            title: 'Loadout Index'
        },
        loadout_name: {
            type: 'string',
            title: 'Loadout Name'
        }
    },
    type: 'object',
    required: ['build_id', 'rank', 'total', 'loadout_index', 'loadout_name'],
    title: 'LoadoutRank',
    description: 'A build whose in-game loadout reproduces one of its optimizer results.'
} as const;

export const LoadoutRankRequestSchema = {
    properties: {
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        staged_sells: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Staged Sells'
        },
        staged_mints: {
            items: {
                '$ref': '#/components/schemas/StagedMint'
            },
            type: 'array',
            title: 'Staged Mints'
        },
        loadouts: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/LoadoutRef'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Loadouts'
        }
    },
    type: 'object',
    required: ['profile_id'],
    title: 'LoadoutRankRequest'
} as const;

export const LoadoutRefSchema = {
    properties: {
        index: {
            type: 'integer',
            title: 'Index'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        name: {
            type: 'string',
            title: 'Name',
            default: ''
        },
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        ga_handles: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Ga Handles'
        }
    },
    type: 'object',
    required: ['index', 'character', 'vessel_id'],
    title: 'LoadoutRef',
    description: `One in-game loadout preset to look for among a build's results.

Sent by the client rather than read from the profile so the LIVE preset
list is what gets matched — a setup saved from the optimizer but not yet
exported is staged client-side, and a badge that ignored it would tell the
user their fresh save isn't there.  Omit the list entirely to match against
the presets exactly as they sit in the uploaded save.`
} as const;

export const LoadoutsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ParsedLoadoutData'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        used: {
            type: 'integer',
            title: 'Used'
        },
        capacity: {
            type: 'integer',
            title: 'Capacity',
            default: 100
        }
    },
    type: 'object',
    required: ['data', 'count', 'used'],
    title: 'LoadoutsPublic'
} as const;

export const LockedSlotSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        }
    },
    type: 'object',
    required: ['slot_index', 'ga_handle'],
    title: 'LockedSlot',
    description: 'A relic frozen in its exact slot during a single-slot re-optimization.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OptimizeRequestSchema = {
    properties: {
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        staged_sells: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Staged Sells'
        },
        staged_mints: {
            items: {
                '$ref': '#/components/schemas/StagedMint'
            },
            type: 'array',
            title: 'Staged Mints'
        },
        build: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildDefinition'
                },
                {
                    type: 'null'
                }
            ]
        },
        relics: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/OwnedRelic-Input'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relics'
        },
        top_n: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Top N',
            default: 10
        },
        max_per_vessel: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Max Per Vessel',
            default: 3
        }
    },
    type: 'object',
    title: 'OptimizeRequest'
} as const;

export const OwnedRelic_InputSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effects', 'curses', 'is_deep', 'name', 'tier'],
    title: 'OwnedRelic',
    description: 'A relic owned by the player, parsed from save data.'
} as const;

export const OwnedRelic_OutputSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        effect_count: {
            type: 'integer',
            title: 'Effect Count',
            readOnly: true
        },
        curse_count: {
            type: 'integer',
            title: 'Curse Count',
            readOnly: true
        },
        all_effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'All Effects',
            readOnly: true
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effects', 'curses', 'is_deep', 'name', 'tier', 'effect_count', 'curse_count', 'all_effects'],
    title: 'OwnedRelic',
    description: 'A relic owned by the player, parsed from save data.'
} as const;

export const ParsedLoadoutDataSchema = {
    properties: {
        index: {
            type: 'integer',
            title: 'Index'
        },
        hero_type: {
            type: 'integer',
            title: 'Hero Type'
        },
        character: {
            type: 'string',
            title: 'Character'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        vessel_name: {
            type: 'string',
            title: 'Vessel Name'
        },
        slot_colors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Slot Colors'
        },
        ga_handles: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Ga Handles'
        },
        cumulative_effects: {
            items: {
                '$ref': '#/components/schemas/CumulativeEffectGroup'
            },
            type: 'array',
            title: 'Cumulative Effects'
        }
    },
    type: 'object',
    required: ['index', 'hero_type', 'character', 'name', 'vessel_id', 'vessel_name'],
    title: 'ParsedLoadoutData',
    description: `An in-game relic loadout preset, enriched for display.

\`\`index\`\` is the preset's position in the save's preset chain (blob order) and
is the stable key used to address it in write operations. \`\`ga_handles\`\` are the
6 relic handles (0 = empty slot); the client joins them against the slot's relics.`
} as const;

export const ParsedProfileDataSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        relic_count: {
            type: 'integer',
            title: 'Relic Count'
        },
        relics: {
            items: {
                '$ref': '#/components/schemas/ParsedRelicData'
            },
            type: 'array',
            title: 'Relics'
        },
        murks: {
            type: 'integer',
            title: 'Murks',
            default: 0
        },
        presets: {
            items: {
                '$ref': '#/components/schemas/ParsedLoadoutData'
            },
            type: 'array',
            title: 'Presets'
        },
        presets_used: {
            type: 'integer',
            title: 'Presets Used',
            default: 0
        },
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        }
    },
    type: 'object',
    required: ['slot_index', 'name', 'relic_count', 'relics'],
    title: 'ParsedProfileData'
} as const;

export const ParsedRelicDataSchema = {
    properties: {
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effect_1: {
            type: 'integer',
            title: 'Effect 1'
        },
        effect_2: {
            type: 'integer',
            title: 'Effect 2'
        },
        effect_3: {
            type: 'integer',
            title: 'Effect 3'
        },
        curse_1: {
            type: 'integer',
            title: 'Curse 1'
        },
        curse_2: {
            type: 'integer',
            title: 'Curse 2'
        },
        curse_3: {
            type: 'integer',
            title: 'Curse 3'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite',
            default: false
        },
        equipped: {
            type: 'boolean',
            title: 'Equipped',
            default: false
        },
        acquisition_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acquisition Id'
        }
    },
    type: 'object',
    required: ['ga_handle', 'item_id', 'real_id', 'color', 'effect_1', 'effect_2', 'effect_3', 'curse_1', 'curse_2', 'curse_3', 'is_deep', 'name', 'tier'],
    title: 'ParsedRelicData',
    description: 'OwnedRelic data as returned in the upload response (before DB persistence).'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        save_upload_id: {
            type: 'string',
            format: 'uuid',
            title: 'Save Upload Id'
        },
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        murks: {
            type: 'integer',
            title: 'Murks',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'save_upload_id', 'slot_index', 'name'],
    title: 'ProfilePublic'
} as const;

export const ProfilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfilesPublic'
} as const;

export const RelicDeltaSchema = {
    properties: {
        added: {
            type: 'integer',
            title: 'Added',
            default: 0
        },
        removed: {
            type: 'integer',
            title: 'Removed',
            default: 0
        }
    },
    type: 'object',
    title: 'RelicDelta',
    description: 'How many relics were gained/lost versus the previous save.'
} as const;

export const RelicPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        ga_handle: {
            type: 'integer',
            title: 'Ga Handle'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        effect_1: {
            type: 'integer',
            title: 'Effect 1'
        },
        effect_2: {
            type: 'integer',
            title: 'Effect 2'
        },
        effect_3: {
            type: 'integer',
            title: 'Effect 3'
        },
        curse_1: {
            type: 'integer',
            title: 'Curse 1'
        },
        curse_2: {
            type: 'integer',
            title: 'Curse 2'
        },
        curse_3: {
            type: 'integer',
            title: 'Curse 3'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'string',
            title: 'Tier'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite',
            default: false
        },
        equipped: {
            type: 'boolean',
            title: 'Equipped',
            default: false
        },
        acquisition_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acquisition Id'
        }
    },
    type: 'object',
    required: ['id', 'profile_id', 'ga_handle', 'item_id', 'real_id', 'color', 'effect_1', 'effect_2', 'effect_3', 'curse_1', 'curse_2', 'curse_3', 'is_deep', 'name', 'tier'],
    title: 'RelicPublic'
} as const;

export const RelicRefSchema = {
    properties: {
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        name: {
            type: 'string',
            title: 'Name',
            default: ''
        },
        color: {
            type: 'string',
            title: 'Color',
            default: ''
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        tier: {
            type: 'string',
            title: 'Tier',
            default: ''
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep',
            default: false
        },
        still_owned: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Still Owned'
        },
        staged: {
            type: 'boolean',
            title: 'Staged',
            default: false
        }
    },
    type: 'object',
    required: ['real_id'],
    title: 'RelicRef',
    description: `Lightweight relic identity for change display (no ga_handle — unstable).

\`\`tier\`\`/\`\`is_deep\`\` are display metadata so a change list can describe a
relic the way the inventory does, without a second lookup.  \`\`still_owned\`\`
answers the question the name alone cannot: a relic that dropped out of a
build's best layout may or may not still be in the save, and those two are
very different pieces of news.  It stays None where nothing checked (older
snapshots, and the persisted layouts, which are inventory-agnostic).`
} as const;

export const RelicsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RelicPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RelicsPublic'
} as const;

export const RitesKeeperSchema = {
    properties: {
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        color: {
            type: 'string',
            title: 'Color'
        },
        tier: {
            type: 'integer',
            title: 'Tier'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        },
        builds: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Builds'
        },
        build_ranks: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Build Ranks',
            default: []
        },
        reason: {
            type: 'string',
            title: 'Reason',
            default: 'build'
        }
    },
    type: 'object',
    required: ['real_id', 'item_id', 'color', 'tier', 'is_deep', 'name', 'effects', 'curses', 'builds'],
    title: 'RitesKeeper',
    description: "A generated relic worth keeping, and which builds' top-N use it."
} as const;

export const RitesPlanResponseSchema = {
    properties: {
        keepers: {
            items: {
                '$ref': '#/components/schemas/RitesKeeper'
            },
            type: 'array',
            title: 'Keepers'
        },
        generated: {
            type: 'integer',
            title: 'Generated'
        },
        kept: {
            type: 'integer',
            title: 'Kept'
        },
        duds: {
            type: 'integer',
            title: 'Duds'
        },
        murk_before: {
            type: 'integer',
            title: 'Murk Before'
        },
        murk_after: {
            type: 'integer',
            title: 'Murk After'
        },
        murk_cost: {
            type: 'integer',
            title: 'Murk Cost'
        },
        murk_refunded: {
            type: 'integer',
            title: 'Murk Refunded'
        },
        murk_delta: {
            type: 'integer',
            title: 'Murk Delta'
        },
        limited_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limited By'
        },
        add_capacity: {
            type: 'integer',
            title: 'Add Capacity'
        },
        storage_left: {
            type: 'integer',
            title: 'Storage Left'
        },
        pending_sold: {
            type: 'integer',
            title: 'Pending Sold',
            default: 0
        },
        pending_sold_refund: {
            type: 'integer',
            title: 'Pending Sold Refund',
            default: 0
        }
    },
    type: 'object',
    required: ['keepers', 'generated', 'kept', 'duds', 'murk_before', 'murk_after', 'murk_cost', 'murk_refunded', 'murk_delta', 'add_capacity', 'storage_left'],
    title: 'RitesPlanResponse',
    description: 'The plan a bulk-purchase + cull request produces (nothing is written yet).'
} as const;

export const RollRelicRequestSchema = {
    properties: {
        is_deep: {
            type: 'boolean',
            title: 'Is Deep',
            default: false
        },
        version: {
            type: 'string',
            title: 'Version',
            default: '1.03'
        },
        mode: {
            type: 'string',
            title: 'Mode',
            default: 'random'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        tier: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tier'
        },
        seed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed'
        }
    },
    type: 'object',
    title: 'RollRelicRequest',
    description: 'Parameters for one relic-purchase roll.'
} as const;

export const SaveComparisonSchema = {
    properties: {
        compared: {
            type: 'boolean',
            title: 'Compared',
            default: true
        },
        reason: {
            type: 'string',
            title: 'Reason',
            default: 'ok'
        },
        restarted_slots: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Restarted Slots'
        }
    },
    type: 'object',
    title: 'SaveComparison',
    description: `Whether this upload was diffed against the previous save, and why not.

The comparison is only meaningful within one game account and one character
(see saves._account_reason / _restarted_slots).  Suppressing it silently
reads exactly like "nothing changed", so the verdict rides along with the
upload response and the page says which it was.`
} as const;

export const SaveStatusPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        uploaded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uploaded At'
        },
        profile_count: {
            type: 'integer',
            title: 'Profile Count'
        },
        profile_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Profile Names'
        }
    },
    type: 'object',
    required: ['id', 'platform', 'profile_count', 'profile_names'],
    title: 'SaveStatusPublic',
    description: "Lightweight status of the user's most recent save upload."
} as const;

export const SlotAlternativeRequestSchema = {
    properties: {
        build_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        staged_sells: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Staged Sells'
        },
        staged_mints: {
            items: {
                '$ref': '#/components/schemas/StagedMint'
            },
            type: 'array',
            title: 'Staged Mints'
        },
        build: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildDefinition'
                },
                {
                    type: 'null'
                }
            ]
        },
        relics: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/OwnedRelic-Input'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relics'
        },
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        struck_slot_index: {
            type: 'integer',
            title: 'Struck Slot Index'
        },
        locked_slots: {
            items: {
                '$ref': '#/components/schemas/LockedSlot'
            },
            type: 'array',
            title: 'Locked Slots'
        },
        excluded_ga_handles: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Excluded Ga Handles'
        }
    },
    type: 'object',
    required: ['vessel_id', 'struck_slot_index'],
    title: 'SlotAlternativeRequest',
    description: `Re-optimize a single vessel slot, freezing every other slot in place.

Powers the "strike a relic" UI: keep each relic in \`\`locked_slots\`\` in its
exact slot, exclude the struck relic(s), and re-fill only
\`\`struck_slot_index\`\` with the next-best relic.  Freezing positions (rather
than positionless pinning) guarantees the rest of the layout — and its
scores — stay put, so the total moves only as a function of the struck slot.
Same dual-mode inventory inputs as :class:\`OptimizeRequest\` (DB mode =
build_id + profile_id; inline mode = build + relics).  Persists nothing.`
} as const;

export const SlotAssignmentSchema = {
    properties: {
        slot_index: {
            type: 'integer',
            title: 'Slot Index'
        },
        slot_color: {
            type: 'string',
            title: 'Slot Color'
        },
        is_deep: {
            type: 'boolean',
            title: 'Is Deep'
        },
        relic: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OwnedRelic-Output'
                },
                {
                    type: 'null'
                }
            ]
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        breakdown: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Breakdown'
        }
    },
    type: 'object',
    required: ['slot_index', 'slot_color', 'is_deep', 'score', 'breakdown'],
    title: 'SlotAssignment',
    description: 'A relic assigned to one vessel slot.'
} as const;

export const SnapshotQuerySchema = {
    properties: {
        build_id: {
            type: 'string',
            format: 'uuid',
            title: 'Build Id'
        },
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        staged_sells: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Staged Sells'
        },
        staged_mints: {
            items: {
                '$ref': '#/components/schemas/StagedMint'
            },
            type: 'array',
            title: 'Staged Mints'
        }
    },
    type: 'object',
    required: ['build_id', 'profile_id'],
    title: 'SnapshotQuery',
    description: `Freshness query for a build+profile's cached optimization.

\`\`staged_sells\`\`/\`\`staged_mints\`\` describe the client's staged in-app diff
(same semantics as OptimizeRequest): freshness is then evaluated against
the EFFECTIVE inventory, so a snapshot written by a staged run is served
back to the same staged state — and, because hashes are content-based, to
the pure state that results from actually exporting + re-uploading it.`
} as const;

export const SnapshotResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/VesselResult'
            },
            type: 'array',
            title: 'Results'
        },
        last_change: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BuildChange'
                },
                {
                    type: 'null'
                }
            ]
        },
        computed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Computed At'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'SnapshotResponse',
    description: 'Cached optimization results from a fresh snapshot.'
} as const;

export const StagedMintSchema = {
    properties: {
        handle: {
            type: 'integer',
            title: 'Handle'
        },
        real_id: {
            type: 'integer',
            title: 'Real Id'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        curses: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Curses'
        }
    },
    type: 'object',
    required: ['handle', 'real_id', 'effects', 'curses'],
    title: 'StagedMint',
    description: `A staged (not-yet-exported) Relic Rites purchase, passed per-request.

\`\`handle\`\` is a client-assigned SYNTHETIC ga_handle and must be negative:
real handles always carry the relic type nibble in their top bits
(\`\`handle & 0xF0000000 == ITEM_TYPE_RELIC\`\`, see nrplanner/writer.py), so
as u32 they are always large positive values — the ranges cannot collide.
The client uses the same synthetic handle consistently across optimizer
requests, results, staged loadouts, and export-time substitution with the
real handle assigned by ghost resurrection.`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UploadResponseSchema = {
    properties: {
        platform: {
            type: 'string',
            title: 'Platform'
        },
        profile_count: {
            type: 'integer',
            title: 'Profile Count'
        },
        profiles: {
            items: {
                '$ref': '#/components/schemas/ParsedProfileData'
            },
            type: 'array',
            title: 'Profiles'
        },
        save_upload_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Save Upload Id'
        },
        persisted: {
            type: 'boolean',
            title: 'Persisted',
            default: false
        },
        relic_delta: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RelicDelta'
                },
                {
                    type: 'null'
                }
            ]
        },
        comparison: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SaveComparison'
                },
                {
                    type: 'null'
                }
            ]
        },
        affected_builds: {
            items: {
                '$ref': '#/components/schemas/BuildChange'
            },
            type: 'array',
            title: 'Affected Builds'
        }
    },
    type: 'object',
    required: ['platform', 'profile_count', 'profiles'],
    title: 'UploadResponse'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VesselResultSchema = {
    properties: {
        vessel_id: {
            type: 'integer',
            title: 'Vessel Id'
        },
        vessel_name: {
            type: 'string',
            title: 'Vessel Name'
        },
        vessel_character: {
            type: 'string',
            title: 'Vessel Character'
        },
        unlock_flag: {
            type: 'integer',
            title: 'Unlock Flag'
        },
        slot_colors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Slot Colors'
        },
        assignments: {
            items: {
                '$ref': '#/components/schemas/SlotAssignment'
            },
            type: 'array',
            title: 'Assignments'
        },
        total_score: {
            type: 'integer',
            title: 'Total Score'
        },
        meets_requirements: {
            type: 'boolean',
            title: 'Meets Requirements',
            default: true
        },
        missing_requirements: {
            items: {
                anyOf: [
                    {
                        type: 'integer'
                    },
                    {
                        type: 'string'
                    }
                ]
            },
            type: 'array',
            title: 'Missing Requirements'
        },
        search_truncated: {
            type: 'boolean',
            title: 'Search Truncated',
            default: false
        },
        cumulative_effects: {
            items: {
                '$ref': '#/components/schemas/CumulativeEffectGroup'
            },
            type: 'array',
            title: 'Cumulative Effects'
        }
    },
    type: 'object',
    required: ['vessel_id', 'vessel_name', 'vessel_character', 'unlock_flag', 'slot_colors', 'assignments', 'total_score'],
    title: 'VesselResult',
    description: 'Optimization result for a single vessel. Ready as FastAPI response.'
} as const;

export const WeightGroupSchema = {
    properties: {
        weight: {
            type: 'integer',
            title: 'Weight'
        },
        effects: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Effects'
        },
        families: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Families'
        }
    },
    type: 'object',
    required: ['weight'],
    title: 'WeightGroup',
    description: 'A user-defined group of effects/families sharing a scoring weight.'
} as const;