// This file is auto-generated by @hey-api/openapi-ts
// Manually extended with planner services (Game, Saves, Builds, Optimize)

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
  LoginLoginAccessTokenData, LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData, LoginRecoverPasswordResponse,
  LoginResetPasswordData, LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData, PrivateCreateUserResponse,
  UsersReadUsersData, UsersReadUsersResponse,
  UsersCreateUserData, UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData, UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse,
  UsersRegisterUserData, UsersRegisterUserResponse,
  UsersReadUserByIdData, UsersReadUserByIdResponse,
  UsersUpdateUserData, UsersUpdateUserResponse,
  UsersDeleteUserData, UsersDeleteUserResponse,
  UtilsTestEmailData, UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from './types.gen';

// ---------------------------------------------------------------------------
// Planner types (will be replaced by generate-client once backend is running)
// ---------------------------------------------------------------------------

export interface ParsedRelicData {
  ga_handle: number
  item_id: number
  real_id: number
  color: string
  effect_1: number
  effect_2: number
  effect_3: number
  curse_1: number
  curse_2: number
  curse_3: number
  is_deep: boolean
  name: string
  tier: string
}

export interface ParsedCharacterData {
  slot_index: number
  name: string
  relic_count: number
  relics: ParsedRelicData[]
  id?: string | null
}

export interface UploadResponse {
  platform: string
  character_count: number
  characters: ParsedCharacterData[]
  save_upload_id?: string | null
  persisted: boolean
}

export interface CharacterPublic {
  id: string
  save_upload_id: string
  slot_index: number
  name: string
}

export interface CharactersPublic {
  data: CharacterPublic[]
  count: number
}

export interface RelicPublic {
  id: string
  character_id: string
  ga_handle: number
  item_id: number
  real_id: number
  color: string
  effect_1: number
  effect_2: number
  effect_3: number
  curse_1: number
  curse_2: number
  curse_3: number
  is_deep: boolean
  name: string
  tier: string
}

export interface RelicsPublic {
  data: RelicPublic[]
  count: number
}

export interface BuildPublic {
  id: string
  owner_id: string
  name: string
  character: string
  tiers: Record<string, number[]>
  family_tiers: Record<string, string[]>
  include_deep: boolean
  curse_max: number
  created_at?: string | null
  updated_at?: string | null
}

export interface BuildsPublic {
  data: BuildPublic[]
  count: number
}

export interface BuildCreate {
  name: string
  character: string
}

export interface BuildUpdate {
  name?: string | null
  character?: string | null
  tiers?: Record<string, number[]> | null
  family_tiers?: Record<string, string[]> | null
  include_deep?: boolean | null
  curse_max?: number | null
}

export interface SlotAssignment {
  slot_index: number
  slot_color: string
  is_deep: boolean
  relic?: RelicPublic | null
  score: number
  breakdown: Record<string, unknown>[]
}

export interface VesselResult {
  vessel_id: number
  vessel_name: string
  vessel_character: string
  unlock_flag: number
  slot_colors: string[]
  assignments: SlotAssignment[]
  total_score: number
  meets_requirements: boolean
  missing_requirements: (number | string)[]
}

export interface OptimizeRequest {
  // DB mode
  build_id?: string | null
  character_id?: string | null
  // Inline mode
  build?: Record<string, unknown> | null
  relics?: RelicPublic[] | null
  character_name?: string | null
  // Common
  top_n?: number
  max_per_vessel?: number
}

// ---------------------------------------------------------------------------
// Game data service
// ---------------------------------------------------------------------------

export class GameService {
  public static getEffects(): CancelablePromise<Record<string, unknown>[]> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/effects',
    });
  }

  public static getFamilies(): CancelablePromise<Record<string, unknown>[]> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/families',
    });
  }

  public static getCharacters(): CancelablePromise<{ name: string; hero_type: number }[]> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/characters',
    });
  }

  public static getVessels(data: { heroType: number }): CancelablePromise<Record<string, unknown>[]> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/vessels/{hero_type}',
      path: { hero_type: data.heroType },
    });
  }

  public static getTiers(): CancelablePromise<Record<string, unknown>[]> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/tiers',
    });
  }

  public static getColors(): CancelablePromise<Record<string, string>> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/game/colors',
    });
  }
}

// ---------------------------------------------------------------------------
// Save file service
// ---------------------------------------------------------------------------

export class SavesService {
  public static uploadSave(data: { formData: { file: File } }): CancelablePromise<UploadResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/saves/upload',
      formData: data.formData,
      mediaType: 'multipart/form-data',
      errors: { 400: 'Bad Request', 422: 'Validation Error' },
    });
  }

  public static listCharacters(): CancelablePromise<CharactersPublic> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/saves/characters',
    });
  }

  public static getCharacterRelics(data: { characterId: string }): CancelablePromise<RelicsPublic> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/saves/characters/{character_id}/relics',
      path: { character_id: data.characterId },
      errors: { 403: 'Forbidden', 404: 'Not Found' },
    });
  }
}

// ---------------------------------------------------------------------------
// Builds service
// ---------------------------------------------------------------------------

export class BuildsService {
  public static listBuilds(data: { skip?: number; limit?: number } = {}): CancelablePromise<BuildsPublic> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/builds/',
      query: { skip: data.skip, limit: data.limit },
    });
  }

  public static createBuild(data: { requestBody: BuildCreate }): CancelablePromise<BuildPublic> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/builds/',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: { 422: 'Validation Error' },
    });
  }

  public static getBuild(data: { buildId: string }): CancelablePromise<BuildPublic> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/builds/{build_id}',
      path: { build_id: data.buildId },
      errors: { 403: 'Forbidden', 404: 'Not Found' },
    });
  }

  public static updateBuild(data: { buildId: string; requestBody: BuildUpdate }): CancelablePromise<BuildPublic> {
    return __request(OpenAPI, {
      method: 'PUT',
      url: '/api/v1/builds/{build_id}',
      path: { build_id: data.buildId },
      body: data.requestBody,
      mediaType: 'application/json',
      errors: { 403: 'Forbidden', 404: 'Not Found', 422: 'Validation Error' },
    });
  }

  public static deleteBuild(data: { buildId: string }): CancelablePromise<{ message: string }> {
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/builds/{build_id}',
      path: { build_id: data.buildId },
      errors: { 403: 'Forbidden', 404: 'Not Found' },
    });
  }
}

// ---------------------------------------------------------------------------
// Optimization service
// ---------------------------------------------------------------------------

export class OptimizeService {
  public static runOptimize(data: { requestBody: OptimizeRequest }): CancelablePromise<VesselResult[]> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/optimize/',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: { 401: 'Unauthorized', 422: 'Validation Error' },
    });
  }
}

// ---------------------------------------------------------------------------
// Login service (unchanged from generated)
// ---------------------------------------------------------------------------

export class LoginService {
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: { 422: 'Validation Error' }
        });
    }

    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }

    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: { email: data.email },
            errors: { 422: 'Validation Error' }
        });
    }

    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: { email: data.email },
            errors: { 422: 'Validation Error' }
        });
    }
}

// ---------------------------------------------------------------------------
// Private service (unchanged)
// ---------------------------------------------------------------------------

export class PrivateService {
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }
}

// ---------------------------------------------------------------------------
// Users service (unchanged)
// ---------------------------------------------------------------------------

export class UsersService {
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: { skip: data.skip, limit: data.limit },
            errors: { 422: 'Validation Error' }
        });
    }

    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, { method: 'GET', url: '/api/v1/users/me' });
    }

    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, { method: 'DELETE', url: '/api/v1/users/me' });
    }

    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: { user_id: data.userId },
            errors: { 422: 'Validation Error' }
        });
    }

    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: { user_id: data.userId },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: { 422: 'Validation Error' }
        });
    }

    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: { user_id: data.userId },
            errors: { 422: 'Validation Error' }
        });
    }
}

// ---------------------------------------------------------------------------
// Utils service (unchanged)
// ---------------------------------------------------------------------------

export class UtilsService {
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: { email_to: data.emailTo },
            errors: { 422: 'Validation Error' }
        });
    }

    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}
