// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_saves_upload_save = {
    file: (Blob | File);
};

export type Body_saves_upload_save_stream = {
    file: (Blob | File);
};

/**
 * How a build's optimal arrangement changed between two optimization inputs.
 *
 * Produced two ways with the same shape: a cheap relic-diff at save-upload
 * time (``potentially_affected`` / ``broken_pin``), and a precise recompute on
 * optimize (``improved`` / ``degraded`` / ``reordered`` / ``unchanged``).
 * ``reliable`` is False when a truncated (non-exhaustive) search makes a small
 * delta untrustworthy.  Relics are referenced by content, never by ga_handle.
 */
export type BuildChange = {
    build_id?: string;
    build_name?: string;
    slot_index?: number;
    status: 'improved' | 'degraded' | 'reordered' | 'unchanged' | 'new' | 'broken_pin' | 'potentially_affected';
    best_before?: (number | null);
    best_after?: (number | null);
    delta?: number;
    entered?: Array<RelicRef>;
    left?: Array<RelicRef>;
    pinned_removed?: Array<RelicRef>;
    relevant_added?: number;
    cause?: ('relics' | 'build_edit' | 'game_data' | 'mixed' | null);
    reliable?: boolean;
};

export type status = 'improved' | 'degraded' | 'reordered' | 'unchanged' | 'new' | 'broken_pin' | 'potentially_affected';

export type BuildCreate = {
    name: string;
    character: string;
    groups?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * User-defined build configuration. Stable API schema.
 */
export type BuildDefinition = {
    id: string;
    name: string;
    character: string;
    groups?: Array<WeightGroup>;
    required_effects?: Array<(number)>;
    required_families?: Array<(string)>;
    excluded_effects?: Array<(number)>;
    excluded_families?: Array<(string)>;
    include_deep?: boolean;
    curse_max?: number;
    default_curse_weight?: number;
    pinned_relics?: Array<(number)>;
    excluded_relics?: Array<(number)>;
    excluded_stacking_categories?: Array<(number)>;
    effect_limits?: {
        [key: string]: (number);
    };
    family_limits?: {
        [key: string]: (number);
    };
    family_weight_floors?: {
        [key: string]: (number);
    };
};

export type BuildPublic = {
    id: string;
    owner_id: string;
    name: string;
    character: string;
    groups?: Array<{
        [key: string]: unknown;
    }>;
    required_effects?: Array<(number)>;
    required_families?: Array<(string)>;
    excluded_effects?: Array<(number)>;
    excluded_families?: Array<(string)>;
    include_deep: boolean;
    curse_max: number;
    default_curse_weight: number;
    pinned_relics?: Array<(number)>;
    excluded_stacking_categories?: Array<(number)>;
    effect_limits?: {
        [key: string]: (number);
    };
    family_limits?: {
        [key: string]: (number);
    };
    family_weight_floors?: {
        [key: string]: (number);
    };
    is_featured: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * A build's most recent optimization change.
 *
 * Embeds the full :class:`BuildChange` so the frontend can render rich,
 * relic-aware change text (verdict + relative % + which relics moved) and
 * filter on ``reviewed`` — all without a full snapshot load.  Deciding which
 * changes are "interesting" is left to the frontend formatter.
 */
export type BuildSnapshotSummary = {
    build_id: string;
    change?: (BuildChange | null);
    reviewed?: boolean;
    best_score?: number;
    computed_at?: (string | null);
};

export type BuildsPublic = {
    data: Array<BuildPublic>;
    count: number;
};

export type BuildUpdate = {
    name?: (string | null);
    character?: (string | null);
    groups?: (Array<{
    [key: string]: unknown;
}> | null);
    required_effects?: (Array<(number)> | null);
    required_families?: (Array<(string)> | null);
    excluded_effects?: (Array<(number)> | null);
    excluded_families?: (Array<(string)> | null);
    include_deep?: (boolean | null);
    curse_max?: (number | null);
    default_curse_weight?: (number | null);
    pinned_relics?: (Array<(number)> | null);
    excluded_stacking_categories?: (Array<(number)> | null);
    effect_limits?: ({
    [key: string]: (number);
} | null);
    family_limits?: ({
    [key: string]: (number);
} | null);
    family_weight_floors?: ({
    [key: string]: (number);
} | null);
};

/**
 * Cumulative in-game bonus for one effect family across a whole vessel.
 *
 * Computed at serve time by nrplanner.cumulative.summarize_cumulative_effects
 * from the curated per-effect values in resources/json/effect_bonus_values.json.
 * Self-stackable numeric effects (incl. family-less singletons) produce a group;
 * conditional ones (e.g. "at low HP") set ``conditional`` so the UI can badge them.
 */
export type CumulativeEffectGroup = {
    family: string;
    mode: 'multiplicative' | 'multiplicative_reduction' | 'additive_flat';
    unit: string;
    tiers: Array<CumulativeEffectTier>;
    cumulative_value: number;
    bonus_percent?: (number | null);
    bonus_display: string;
    conditional?: (string | null);
    is_top?: boolean;
};

export type mode = 'multiplicative' | 'multiplicative_reduction' | 'additive_flat';

/**
 * One tier within a stacked-effect group (e.g. '+4' present 3 times).
 */
export type CumulativeEffectTier = {
    name: string;
    tier_label: string;
    count: number;
};

export type DebugExportRequest = {
    mode?: 'view' | 'full';
    build_id?: (string | null);
    profile_id?: (string | null);
    results?: (Array<{
    [key: string]: unknown;
}> | null);
    note?: (string | null);
};

export type mode2 = 'view' | 'full';

export type FeaturedBuildPublic = {
    id: string;
    name: string;
    character: string;
    groups?: Array<{
        [key: string]: unknown;
    }>;
    required_effects?: Array<(number)>;
    required_families?: Array<(string)>;
    excluded_effects?: Array<(number)>;
    excluded_families?: Array<(string)>;
    include_deep: boolean;
    curse_max: number;
    default_curse_weight: number;
    pinned_relics?: Array<(number)>;
    excluded_stacking_categories?: Array<(number)>;
    effect_limits?: {
        [key: string]: (number);
    };
    family_limits?: {
        [key: string]: (number);
    };
    family_weight_floors?: {
        [key: string]: (number);
    };
    owner_name?: (string | null);
    created_at?: (string | null);
};

export type FeaturedBuildsPublic = {
    data: Array<FeaturedBuildPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * A relic frozen in its exact slot during a single-slot re-optimization.
 */
export type LockedSlot = {
    slot_index: number;
    ga_handle: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OptimizeRequest = {
    build_id?: (string | null);
    profile_id?: (string | null);
    build?: (BuildDefinition | null);
    relics?: (Array<OwnedRelic_Input> | null);
    top_n?: number;
    max_per_vessel?: number;
};

/**
 * A relic owned by the player, parsed from save data.
 */
export type OwnedRelic_Input = {
    ga_handle: number;
    item_id: number;
    real_id: number;
    color: string;
    effects: Array<(number)>;
    curses: Array<(number)>;
    is_deep: boolean;
    name: string;
    tier: string;
};

/**
 * A relic owned by the player, parsed from save data.
 */
export type OwnedRelic_Output = {
    ga_handle: number;
    item_id: number;
    real_id: number;
    color: string;
    effects: Array<(number)>;
    curses: Array<(number)>;
    is_deep: boolean;
    name: string;
    tier: string;
    readonly effect_count: number;
    readonly curse_count: number;
    readonly all_effects: Array<(number)>;
};

export type ParsedProfileData = {
    slot_index: number;
    name: string;
    relic_count: number;
    relics: Array<ParsedRelicData>;
    id?: (string | null);
};

/**
 * OwnedRelic data as returned in the upload response (before DB persistence).
 */
export type ParsedRelicData = {
    ga_handle: number;
    item_id: number;
    real_id: number;
    color: string;
    effect_1: number;
    effect_2: number;
    effect_3: number;
    curse_1: number;
    curse_2: number;
    curse_3: number;
    is_deep: boolean;
    name: string;
    tier: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfilePublic = {
    id: string;
    save_upload_id: string;
    slot_index: number;
    name: string;
};

export type ProfilesPublic = {
    data: Array<ProfilePublic>;
    count: number;
};

/**
 * How many relics were gained/lost versus the previous save.
 */
export type RelicDelta = {
    added?: number;
    removed?: number;
};

export type RelicPublic = {
    id: string;
    profile_id: string;
    ga_handle: number;
    item_id: number;
    real_id: number;
    color: string;
    effect_1: number;
    effect_2: number;
    effect_3: number;
    curse_1: number;
    curse_2: number;
    curse_3: number;
    is_deep: boolean;
    name: string;
    tier: string;
};

/**
 * Lightweight relic identity for change display (no ga_handle — unstable).
 */
export type RelicRef = {
    real_id: number;
    name?: string;
    color?: string;
    effects?: Array<(number)>;
    curses?: Array<(number)>;
};

export type RelicsPublic = {
    data: Array<RelicPublic>;
    count: number;
};

/**
 * Lightweight status of the user's most recent save upload.
 */
export type SaveStatusPublic = {
    id: string;
    platform: string;
    uploaded_at?: (string | null);
    profile_count: number;
    profile_names: Array<(string)>;
};

/**
 * Re-optimize a single vessel slot, freezing every other slot in place.
 *
 * Powers the "strike a relic" UI: keep each relic in ``locked_slots`` in its
 * exact slot, exclude the struck relic(s), and re-fill only
 * ``struck_slot_index`` with the next-best relic.  Freezing positions (rather
 * than positionless pinning) guarantees the rest of the layout — and its
 * scores — stay put, so the total moves only as a function of the struck slot.
 * Same dual-mode inventory inputs as :class:`OptimizeRequest` (DB mode =
 * build_id + profile_id; inline mode = build + relics).  Persists nothing.
 */
export type SlotAlternativeRequest = {
    build_id?: (string | null);
    profile_id?: (string | null);
    build?: (BuildDefinition | null);
    relics?: (Array<OwnedRelic_Input> | null);
    vessel_id: number;
    struck_slot_index: number;
    locked_slots?: Array<LockedSlot>;
    excluded_ga_handles?: Array<(number)>;
};

/**
 * A relic assigned to one vessel slot.
 */
export type SlotAssignment = {
    slot_index: number;
    slot_color: string;
    is_deep: boolean;
    relic?: (OwnedRelic_Output | null);
    score: number;
    breakdown: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Cached optimization results from a fresh snapshot.
 */
export type SnapshotResponse = {
    results: Array<VesselResult>;
    last_change?: (BuildChange | null);
    computed_at?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UploadResponse = {
    platform: string;
    profile_count: number;
    profiles: Array<ParsedProfileData>;
    save_upload_id?: (string | null);
    persisted?: boolean;
    relic_delta?: (RelicDelta | null);
    affected_builds?: Array<BuildChange>;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Optimization result for a single vessel. Ready as FastAPI response.
 */
export type VesselResult = {
    vessel_id: number;
    vessel_name: string;
    vessel_character: string;
    unlock_flag: number;
    slot_colors: Array<(string)>;
    assignments: Array<SlotAssignment>;
    total_score: number;
    meets_requirements?: boolean;
    missing_requirements?: Array<(number | string)>;
    search_truncated?: boolean;
    cumulative_effects?: Array<CumulativeEffectGroup>;
};

/**
 * A user-defined group of effects/families sharing a scoring weight.
 */
export type WeightGroup = {
    weight: number;
    effects?: Array<(number)>;
    families?: Array<(string)>;
};

export type BuildsListBuildsData = {
    limit?: number;
    skip?: number;
};

export type BuildsListBuildsResponse = (BuildsPublic);

export type BuildsCreateBuildData = {
    requestBody: BuildCreate;
};

export type BuildsCreateBuildResponse = (BuildPublic);

export type BuildsListFeaturedBuildsData = {
    limit?: number;
    skip?: number;
};

export type BuildsListFeaturedBuildsResponse = (FeaturedBuildsPublic);

export type BuildsGetBuildData = {
    buildId: string;
};

export type BuildsGetBuildResponse = (BuildPublic);

export type BuildsUpdateBuildData = {
    buildId: string;
    requestBody: BuildUpdate;
};

export type BuildsUpdateBuildResponse = (BuildPublic);

export type BuildsDeleteBuildData = {
    buildId: string;
};

export type BuildsDeleteBuildResponse = (Message);

export type BuildsToggleFeaturedData = {
    buildId: string;
};

export type BuildsToggleFeaturedResponse = (BuildPublic);

export type BuildsCloneBuildData = {
    buildId: string;
};

export type BuildsCloneBuildResponse = (BuildPublic);

export type DebugExportDebugStateData = {
    requestBody: DebugExportRequest;
};

export type DebugExportDebugStateResponse = ({
    [key: string]: unknown;
});

export type GameGetEffectsResponse = (Array<{
    [key: string]: unknown;
}>);

export type GameGetFamiliesResponse = (Array<{
    [key: string]: unknown;
}>);

export type GameGetCharactersResponse = (Array<{
    [key: string]: unknown;
}>);

export type GameGetVesselsData = {
    heroType: number;
};

export type GameGetVesselsResponse = (Array<{
    [key: string]: unknown;
}>);

export type GameGetStackingCategoriesResponse = (Array<{
    [key: string]: unknown;
}>);

export type GameGetColorsResponse = ({
    [key: string]: (string);
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OauthLoginGoogleResponse = (unknown);

export type OauthGoogleCallbackData = {
    code?: (string | null);
    error?: (string | null);
    state?: (string | null);
};

export type OauthGoogleCallbackResponse = (unknown);

export type OptimizeRunOptimizeData = {
    requestBody: OptimizeRequest;
};

export type OptimizeRunOptimizeResponse = (Array<VesselResult>);

export type OptimizeRunOptimizeStreamData = {
    requestBody: OptimizeRequest;
};

export type OptimizeRunOptimizeStreamResponse = (unknown);

export type OptimizeOptimizeSlotAlternativeData = {
    requestBody: SlotAlternativeRequest;
};

export type OptimizeOptimizeSlotAlternativeResponse = ((VesselResult | null));

export type OptimizeGetSnapshotData = {
    buildId: string;
    profileId: string;
};

export type OptimizeGetSnapshotResponse = ((SnapshotResponse | null));

export type OptimizeListBuildSummariesResponse = (Array<BuildSnapshotSummary>);

export type OptimizeMarkChangeReviewedData = {
    buildId: string;
};

export type OptimizeMarkChangeReviewedResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SavesUploadSaveData = {
    formData: Body_saves_upload_save;
};

export type SavesUploadSaveResponse = (UploadResponse);

export type SavesUploadSaveStreamData = {
    formData: Body_saves_upload_save_stream;
};

export type SavesUploadSaveStreamResponse = (unknown);

export type SavesGetSaveStatusResponse = ((SaveStatusPublic | null));

export type SavesListProfilesResponse = (ProfilesPublic);

export type SavesGetProfileRelicsData = {
    profileId: string;
};

export type SavesGetProfileRelicsResponse = (RelicsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);