"""add default_curse_weight to build

Revision ID: 2b1545b90ad5
Revises: c0d1e2f3a4b5
Create Date: 2026-03-09 08:43:55.143977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1545b90ad5'
down_revision = 'c0d1e2f3a4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('default_curse_weight', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'default_curse_weight')
    # ### end Alembic commands ###
