/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUploadRouteImport } from './routes/_layout/upload'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOptimizeRouteImport } from './routes/_layout/optimize'
import { Route as LayoutInventoryRouteImport } from './routes/_layout/inventory'
import { Route as LayoutBuildsRouteImport } from './routes/_layout/builds'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBuildsBuildIdRouteImport } from './routes/_layout/builds.$buildId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUploadRoute = LayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOptimizeRoute = LayoutOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryRoute = LayoutInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildsRoute = LayoutBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildsBuildIdRoute = LayoutBuildsBuildIdRouteImport.update({
  id: '/$buildId',
  path: '/$buildId',
  getParentRoute: () => LayoutBuildsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/builds': typeof LayoutBuildsRouteWithChildren
  '/inventory': typeof LayoutInventoryRoute
  '/optimize': typeof LayoutOptimizeRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/builds/$buildId': typeof LayoutBuildsBuildIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/builds': typeof LayoutBuildsRouteWithChildren
  '/inventory': typeof LayoutInventoryRoute
  '/optimize': typeof LayoutOptimizeRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/': typeof LayoutIndexRoute
  '/builds/$buildId': typeof LayoutBuildsBuildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/builds': typeof LayoutBuildsRouteWithChildren
  '/_layout/inventory': typeof LayoutInventoryRoute
  '/_layout/optimize': typeof LayoutOptimizeRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/upload': typeof LayoutUploadRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/builds/$buildId': typeof LayoutBuildsBuildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/builds'
    | '/inventory'
    | '/optimize'
    | '/settings'
    | '/upload'
    | '/builds/$buildId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/builds'
    | '/inventory'
    | '/optimize'
    | '/settings'
    | '/upload'
    | '/'
    | '/builds/$buildId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/builds'
    | '/_layout/inventory'
    | '/_layout/optimize'
    | '/_layout/settings'
    | '/_layout/upload'
    | '/_layout/'
    | '/_layout/builds/$buildId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/optimize': {
      id: '/_layout/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof LayoutOptimizeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory': {
      id: '/_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof LayoutInventoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builds': {
      id: '/_layout/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof LayoutBuildsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builds/$buildId': {
      id: '/_layout/builds/$buildId'
      path: '/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof LayoutBuildsBuildIdRouteImport
      parentRoute: typeof LayoutBuildsRoute
    }
  }
}

interface LayoutBuildsRouteChildren {
  LayoutBuildsBuildIdRoute: typeof LayoutBuildsBuildIdRoute
}

const LayoutBuildsRouteChildren: LayoutBuildsRouteChildren = {
  LayoutBuildsBuildIdRoute: LayoutBuildsBuildIdRoute,
}

const LayoutBuildsRouteWithChildren = LayoutBuildsRoute._addFileChildren(
  LayoutBuildsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBuildsRoute: typeof LayoutBuildsRouteWithChildren
  LayoutInventoryRoute: typeof LayoutInventoryRoute
  LayoutOptimizeRoute: typeof LayoutOptimizeRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBuildsRoute: LayoutBuildsRouteWithChildren,
  LayoutInventoryRoute: LayoutInventoryRoute,
  LayoutOptimizeRoute: LayoutOptimizeRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUploadRoute: LayoutUploadRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
